---

- name: Copy systemd-timesyncd configuration file
  become: yes
  template:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf

- name: Enable systemd-timesyncd service
  become: yes
  systemd:
    name: systemd-timesyncd.service
    enabled: yes
