---

- name: Blacklist watchdog
  become: yes
  copy:
    dest: /etc/modprobe.d/nowatchdog.conf
    content: "blacklist iTCO_wdt"

- name: Disable watchdog
  become: yes
  modprobe:
    name: iTCO_wdt
    state: absent
