---

- name: Install Firefox
  become: yes
  pacman:
    name: firefox

- name: Install libva drivers
  become: yes
  pacman:
    name:
      - intel-media-driver
      - libva-intel-driver

- name: Create Personal profile directory
  file:
    path: ~/.mozilla/firefox/Personal
    state: directory

- name: Set Personal profile name
  ini_file:
    path: ~/.mozilla/firefox/profiles.ini
    section: Profile0
    option: Name
    value: Personal
    no_extra_spaces: yes

- name: Set Personal profile is relative
  ini_file:
    path: ~/.mozilla/firefox/profiles.ini
    section: Profile0
    option: IsRelative
    value: "1"
    no_extra_spaces: yes

- name: Set Personal profile path
  ini_file:
    path: ~/.mozilla/firefox/profiles.ini
    section: Profile0
    option: Path
    value: Personal
    no_extra_spaces: yes

- name: Copy Personal user.js file
  template:
    src: user.js
    dest: ~/.mozilla/firefox/Personal/user.js

- name: Create Work profile directory
  file:
    path: ~/.mozilla/firefox/Work
    state: directory

- name: Set Work profile name
  ini_file:
    path: ~/.mozilla/firefox/profiles.ini
    section: Profile1
    option: Name
    value: Work
    no_extra_spaces: yes

- name: Set Work profile is relative
  ini_file:
    path: ~/.mozilla/firefox/profiles.ini
    section: Profile1
    option: IsRelative
    value: "1"
    no_extra_spaces: yes

- name: Set Work profile path
  ini_file:
    path: ~/.mozilla/firefox/profiles.ini
    section: Profile1
    option: Path
    value: Work
    no_extra_spaces: yes

- name: Copy Work user.js file
  template:
    src: user.js
    dest: ~/.mozilla/firefox/Work/user.js

- name: Do not start with last profile
  ini_file:
    path: ~/.mozilla/firefox/profiles.ini
    section: General
    option: StartWithLastProfile
    value: "0"
    no_extra_spaces: yes

- name: Create local applications directory
  file:
    path: ~/.local/share/applications
    state: directory

- name: Copy firefox.desktop
  copy:
    src: /usr/share/applications/firefox.desktop
    dest: ~/.local/share/applications/firefox.desktop
    force: no
    remote_src: yes

- name: Open profile manager on normal action
  ini_file:
    path: ~/.local/share/applications/firefox.desktop
    section: Desktop Entry
    option: Exec
    value: "/usr/lib/firefox/firefox --ProfileManager %u"
    no_extra_spaces: yes

- name: Open profile manager on new window action
  ini_file:
    path: ~/.local/share/applications/firefox.desktop
    section: Desktop Action new-window
    option: Exec
    value: "/usr/lib/firefox/firefox --ProfileManager --new-window %u"
    no_extra_spaces: yes

- name: Open profile manager on new private window action
  ini_file:
    path: ~/.local/share/applications/firefox.desktop
    section: Desktop Action new-private-window
    option: Exec
    value: "/usr/lib/firefox/firefox --ProfileManager --private-window %u"
    no_extra_spaces: yes
