---

- name: Install Chromium
  become: yes
  pacman:
    name: chromium

- name: Create config directory
  file:
    path: ~/.config/
    state: directory

- name: Copy Chromium command line arguments
  template:
    src: chromium-flags.conf
    dest: ~/.config/chromium-flags.conf

- name: Install libva drivers
  become: yes
  pacman:
    name:
      - intel-media-driver
      - libva-intel-driver

- name: Install Flash support
  become: yes
  pacman:
    name: pepper-flash

- name: Install Widevine support
  aur:
    name: chromium-widevine
