---

- name: Install extra packages
  pacman:
    name: "{{ item }}"
  with_items:
    - aspell-en
    - aws-cli
    - dconf-editor
    - gimp
    - gnome-tweaks
    - gvim
    - hunspell-en_US
    - inkscape
    - libreoffice-fresh
    - libva-intel-driver
    - steam
    - steam-native-runtime

- name: Install extra AUR packages
  become_user: "{{ user.name }}"
  aur:
    name: "{{ item }}"
  with_items:
    - google-chrome
    - nordvpn-bin
    - slack-desktop
