---

- name: Install GDM
  pacman:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - gdm

- name: Enable GDM
  service:
    name: gdm
    enabled: yes

- name: Copy dconf gdm profile
  template:
    src: gdm
    dest: /etc/dconf/profile/gdm

- name: Create GDM configuration directory
  file:
    path: /etc/dconf/db/gdm.d
    state: directory

- name: Copy GDM configuration
  template:
    src: gdm.conf
    dest: /etc/dconf/db/gdm.d/00-desheffer
  notify:
    - Update dconf
