---

- name: Install GDM
  become: yes
  pacman:
    name: gdm

- name: Enable GDM
  become: yes
  systemd:
    name: gdm.service
    enabled: yes

- name: Copy dconf gdm profile
  become: yes
  template:
    src: gdm
    dest: /etc/dconf/profile/gdm

- name: Create GDM configuration directory
  become: yes
  file:
    path: /etc/dconf/db/gdm.d
    state: directory

- name: Copy GDM configuration
  become: yes
  template:
    src: gdm.conf
    dest: /etc/dconf/db/gdm.d/00-desheffer
  notify:
    - Update dconf
