---

- name: Mask systemd radio service
  become: yes
  systemd:
    name: systemd-rfkill.service
    masked: yes

- name: Mask systemd radio socket
  become: yes
  systemd:
    name: systemd-rfkill.socket
    masked: yes

- name: Disable module-suspend-on-idle
  become: yes
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: "^#?load-module module-suspend-on-idle$"
    line: "#load-module module-suspend-on-idle"
