---

- name: Install TLP
  become: yes
  pacman:
    name: tlp

- name: Copy TLP configuration
  become: yes
  template:
    src: tlp.conf
    dest: /etc/default/tlp

- name: Enable TLP service
  become: yes
  systemd:
    name: tlp.service
    enabled: yes

- name: Enable TLP sleep service
  become: yes
  systemd:
    name: tlp-sleep.service
    enabled: yes

- name: Mask systemd radio service
  become: yes
  systemd:
    name: systemd-rfkill.service
    masked: yes

- name: Mask systemd radio socket
  become: yes
  systemd:
    name: systemd-rfkill.socket
    masked: yes

- name: Install PowerTOP
  become: yes
  pacman:
    name: powertop

- name: Create PowerTOP service
  become: yes
  template:
    src: powertop.service
    dest: /etc/systemd/system/powertop.service
    mode: 0644
