---

- name: Check if wallpaper exists
  stat:
    path: ~/.wallpaper
  register: wallpaper

- name: Download wallpaper
  get_url:
    url: https://raw.githubusercontent.com/GNOME/gnome-backgrounds/gnome-41/backgrounds/Blobs.svg
    dest: ~/.wallpaper
  when: wallpaper.stat.exists == False
