---

- name: Install dotfiles packages
  become: yes
  pacman:
    name:
      - bash-completion
      - the_silver_searcher
      - tmux
      - vim

- name: Clone dotfiles repository
  git:
    repo: "https://github.com/desheffer/dotfiles.git"
    dest: ~/dotfiles
    accept_hostkey: yes
  notify:
    - Install dotfiles
