---

- name: Install dotfiles packages
  become: yes
  pacman:
    name:
      - fzf
      - neovim
      - ripgrep
      - the_silver_searcher
      - tmate
      - tmux
      - zsh

- name: Remove vi
  become: yes
  command: "pacman -R --noconfirm vi"
  register: vi_result
  changed_when: "'Packages' in vi_result.stdout"
  failed_when: False

- name: Install neovim-symlinks
  aur:
    name: neovim-symlinks

- name: Clone dotfiles repository
  git:
    repo: "https://github.com/desheffer/dotfiles.git"
    dest: ~/dotfiles
    accept_hostkey: yes
    update: no
  notify:
    - Install dotfiles

- name: Set zsh as the default shell
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
