---

- name: Install dotfiles packages
  become: yes
  pacman:
    name:
      - the_silver_searcher
      - tmate
      - tmux
      - vim
      - zsh

- name: Remove vi
  become: yes
  command: "pacman -R --noconfirm vi"
  register: vi_result
  changed_when: "'Packages' in vi_result.stdout"
  failed_when: False

- name: Install vi-vim-symlink
  aur:
    name: vi-vim-symlink

- name: Clone dotfiles repository
  git:
    repo: "https://github.com/desheffer/dotfiles.git"
    dest: ~/dotfiles
    accept_hostkey: yes
    update: no
  notify:
    - Install dotfiles

- name: Do not load defaults if ~/.vimrc is missing
  become: yes
  lineinfile:
    path: /etc/vimrc
    regexp: "^\"?let skip_defaults_vim=.*$"
    line: "let skip_defaults_vim=1"

- name: Set zsh as the default shell
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
