---

- name: Install GUI packages
  become: yes
  pacman:
    name:
      - gimp
      - inkscape
      - libreoffice-fresh
      - qalculate-gtk
      - steam
      - transmission-gtk
      - vlc
      - xsel

- name: Install extra GUI packages
  aur:
    name:
      - color-picker
      - lastpass
      - slack-desktop
      - zoom

- name: Remove steam.desktop
  file:
    path: ~/Desktop/steam.desktop
    state: absent
