---

- name: Install GUI packages
  become: yes
  pacman:
    name:
      - gimp
      - gpick
      - inkscape
      - libreoffice-fresh
      - qalculate-gtk
      - steam
      - transmission-gtk

- name: Install extra GUI packages
  aur:
    name:
      - slack-desktop
