---

- name: Install GUI packages
  become: yes
  pacman:
    name:
      - gimp
      - inkscape
      - libreoffice-fresh
      - qalculate-gtk
      - steam

- name: Install extra GUI packages
  aur:
    name:
      - nordvpn-bin
      - slack-desktop
