---

- name: Install GUI packages
  become: yes
  pacman:
    name:
      - gimp
      - inkscape
      - intel-media-driver
      - libreoffice-fresh
      - libva-intel-driver
      - qalculate-gtk
      - steam
      - vlc

- name: Install extra GUI packages
  aur:
    name:
      - chromium-vaapi-bin
      - nordvpn-bin
      - slack-desktop
