---

- name: Install GUI packages
  become: yes
  pacman:
    name:
      - gimp
      - gpick
      - inkscape
      - libreoffice-fresh
      - qalculate-gtk
      - steam
      - transmission-gtk
      - vlc
      - xsel

- name: Install extra GUI packages
  aur:
    name:
      - gpmdp
      - slack-desktop
      - zoom
    skip_installed: true
