---

- name: Install GUI packages
  become: yes
  pacman:
    name:
      - alacritty
      - gimp
      - inkscape
      - libreoffice-fresh
      - qalculate-gtk
      - steam
      - transmission-gtk
      - vlc
      - vulkan-intel
      - xsel

- name: Install extra GUI packages
  aur:
    name:
      - color-picker
      - gpmdp
      - slack-desktop
      - zoom
    skip_installed: true

- name: Copy Alacritty.desktop
  copy:
    src: /usr/share/applications/Alacritty.desktop
    dest: ~/.local/share/applications/Alacritty.desktop
    force: no
    remote_src: yes

- name: Set Alacritty icon
  ini_file:
    path: ~/.local/share/applications/Alacritty.desktop
    section: Desktop Entry
    option: Icon
    value: "terminal"
    no_extra_spaces: yes

- name: Remove steam.desktop
  file:
    path: ~/Desktop/steam.desktop
    state: absent
