---

- name: Install GUI packages
  become: yes
  pacman:
    name:
      - gimp
      - inkscape
      - libreoffice-fresh
      - qalculate-gtk
      - steam
      - transmission-gtk
      - vlc
      - vulkan-intel
      - xsel

- name: Install extra GUI packages
  aur:
    name:
      - color-picker
      - gpmdp
      - slack-desktop
      - zoom
    skip_installed: true

- name: Remove steam.desktop
  file:
    path: ~/Desktop/steam.desktop
    state: absent
