---

- name: Create boot configuration
  command: "bootctl --path=/boot install"
  args:
    creates: /boot/loader/loader.conf

- name: Create boot loader configuration
  template:
    src: loader.conf
    dest: /boot/loader/loader.conf

- name: Get UUID of root partition
  command: "blkid -t TYPE=crypto_LUKS -s UUID -o value"
  register: root_uuid
  changed_when: False

- name: Create boot entry configuration
  template:
    src: arch.conf
    dest: /boot/loader/entries/arch.conf

- name: Copy initial ramdisk configuration
  template:
    src: mkinitcpio.conf
    dest: /etc/mkinitcpio.conf
  notify:
    - Generate ramdisk

- name: Install pacman hook to upgrade systemd-boot
  become_user: "{{ user.name }}"
  aur:
    name: systemd-boot-pacman-hook
