---

- name: Set hostname
  file:
    path: /etc/hostname
    content: "{{ hostname }}"
    force: no

- name: Enable DHCP
  file:
    src: /usr/lib/systemd/system/dhcpcd.service
    dest: /etc/systemd/system/multi-user.target.wants/dhcpcd.service
    state: link
