---

- name: Set hostname
  copy:
    dest: /etc/hostname
    content: "{{ hostname }}"

- name: Enable DHCP
  file:
    src: /usr/lib/systemd/system/dhcpcd.service
    dest: /etc/systemd/system/multi-user.target.wants/dhcpcd.service
    state: link
