---

- name: Copy pacman configuration
  template:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Update pacman
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install base packages
  pacman:
    name: "{{ item }}"
  with_items:
    - base-devel
    - bash
    - bash-completion
    - bc
    - coreutils
    - dialog
    - fwupd
    - git
    - htop
    - jq
    - net-tools
    - reflector
    - rsync
    - the_silver_searcher
    - tmux
    - tree
    - wireless_tools
    - wpa_supplicant

- name: Create pacman hook directory
  file:
    path: /etc/pacman.d/hooks
    state: directory

- name: Copy pacman hook to update mirror list
  template:
    src: mirrorlist.hook
    dest: /etc/pacman.d/hooks/mirrorlist.hook
