---

- name: Create user group
  group:
    name: "{{ user.name }}"

- name: Create user
  user:
    name: "{{ user.name }}"
    comment: "{{ user.fullname }}"
    group: "{{ user.name }}"
    uid: 1000
    shell: "{{ user.shell }}"

- name: Create sudo configuration directory
  file:
    path: /etc/sudoers.d
    state: directory

- name: Allow user to sudo
  template:
    src: sudoers.conf
    dest: "/etc/sudoers.d/10-{{ user.name }}"
    validate: "visudo -cf %s"

- name: Set user password
  user:
    name: "{{ user.name }}"
    password: "{{ password | password_hash('sha512') }}"
  when: password

- name: Set root password
  user:
    name: root
    password: "{{ password | password_hash('sha512') }}"
  when: password
