---

- name: Create user group
  group:
    name: "{{ user.name }}"

- name: Create user
  user:
    name: "{{ user.name }}"
    comment: "{{ user.fullname }}"
    password: "{{ user.name | password_hash('sha512') }}"
    update_password: on_create
    group: "{{ user.name }}"
    uid: 1000
    shell: "{{ user.shell }}"

- name: Create sudo configuration directory
  file:
    path: /etc/sudoers.d
    state: directory

- name: Allow user to sudo
  template:
    src: sudoers.conf
    dest: "/etc/sudoers.d/10-{{ user.name }}"
    validate: "visudo -cf %s"
