---

- name: Install network packages
  become: yes
  pacman:
    name:
      - bind-tools
      - net-tools
      - networkmanager
      - nmap
      - speedtest-cli
      - wireless_tools
      - wpa_supplicant

- name: Enable NetworkManager service
  become: yes
  systemd:
    name: NetworkManager.service
    enabled: yes
