---

- name: Install network packages
  become: yes
  pacman:
    name:
      - bind-tools
      - net-tools
      - networkmanager
      - nmap
      - speedtest-cli
      - wireless_tools
      - wpa_supplicant

- name: Enable NetworkManager service
  become: yes
  systemd:
    name: NetworkManager.service
    enabled: yes

- name: Copy resolv.conf
  become: yes
  template:
    src: resolv.conf
    dest: /etc/resolv.static.conf

- name: Link resolv.conf
  become: yes
  file:
    src: /etc/resolv.static.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
