---

- name: Install GNOME base packages
  become: yes
  pacman:
    name:
      - baobab
      - cheese
      - eog
      - evince
      - file-roller
      - gedit
      - gnome-backgrounds
      - gnome-calendar
      - gnome-characters
      - gnome-color-manager
      - gnome-control-center
      - gnome-font-viewer
      - gnome-keyring
      - gnome-screenshot
      - gnome-session
      - gnome-settings-daemon
      - gnome-shell
      - gnome-shell-extensions
      - gnome-terminal
      - gvfs-google
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      - mousetweaks
      - mutter
      - nautilus
      - networkmanager
      - sushi
      - tracker
      - tracker-miners
      - xdg-user-dirs-gtk

- name: Install GNOME extra packages
  become: yes
  pacman:
    name:
      - arc-gtk-theme
      - dconf-editor
      - gnome-tweaks
      - python-psutil

- name: Install GNOME AUR packages
  aur:
    name:
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-topicons-plus-huttli-git
      - numix-icon-theme-pack-git

- name: Copy dconf user profile
  become: yes
  template:
    src: user
    dest: /etc/dconf/profile/user

- name: Create GNOME configuration directory
  become: yes
  file:
    path: /etc/dconf/db/gnome.d
    state: directory

- name: Copy GNOME configuration
  become: yes
  template:
    src: gnome.conf
    dest: /etc/dconf/db/gnome.d/00-desheffer
  notify:
    - Update dconf

- name: Reset favorite-apps
  dconf:
    key: /org/gnome/shell/favorite-apps
    state: absent

- name: Start NetworkManager
  become: yes
  systemd:
    name: NetworkManager.service
    enabled: yes
    state: started
