---

- name: Install GNOME base packages
  become: yes
  pacman:
    name:
      - baobab
      - eog
      - evince
      - file-roller
      - gedit
      - gnome-backgrounds
      - gnome-calendar
      - gnome-characters
      - gnome-color-manager
      - gnome-control-center
      - gnome-disk-utility
      - gnome-font-viewer
      - gnome-keyring
      - gnome-screenshot
      - gnome-session
      - gnome-settings-daemon
      - gnome-shell
      - gnome-shell-extensions
      - gnome-terminal
      - gvfs-google
      - gvfs-mtp
      - mousetweaks
      - mutter
      - nautilus
      - networkmanager
      - sushi
      - totem
      - xdg-user-dirs-gtk

- name: Install GNOME extra packages
  become: yes
  pacman:
    name:
      - arc-gtk-theme
      - dconf-editor
      - gnome-tweaks
      - python-psutil

- name: Install GNOME AUR packages
  aur:
    name:
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-topicons-plus-huttli-git
      - numix-icon-theme-pack-git

- name: Remove libgdm
  become: yes
  command: "pacman -Rdd --noconfirm libgdm"
  register: libgdm_result
  changed_when: "'Packages' in libgdm_result.stdout"
  failed_when: False

- name: Install GDM
  aur:
    name: gdm-plymouth

- name: Copy dconf user profile
  become: yes
  template:
    src: user
    dest: /etc/dconf/profile/user

- name: Create GNOME configuration directory
  become: yes
  file:
    path: /etc/dconf/db/gnome.d
    state: directory

- name: Copy GNOME configuration
  become: yes
  template:
    src: gnome.conf
    dest: /etc/dconf/db/gnome.d/00-desheffer
  notify:
    - Update dconf

- name: Copy dconf gdm profile
  become: yes
  template:
    src: gdm
    dest: /etc/dconf/profile/gdm

- name: Create GDM configuration directory
  become: yes
  file:
    path: /etc/dconf/db/gdm.d
    state: directory

- name: Copy GDM configuration
  become: yes
  template:
    src: gdm.conf
    dest: /etc/dconf/db/gdm.d/00-desheffer
  notify:
    - Update dconf

- name: Reset favorite-apps
  dconf:
    key: /org/gnome/shell/favorite-apps
    state: absent

- name: Mask GDM (non-plymouth) service
  become: yes
  systemd:
    name: gdm.service
    masked: yes

- name: Enable GDM service
  become: yes
  systemd:
    name: gdm-plymouth.service
    enabled: yes

- name: Enable NetworkManager service
  become: yes
  systemd:
    name: NetworkManager.service
    enabled: yes
