---

- name: Install GNOME base packages
  become: yes
  pacman:
    name:
      - baobab
      - eog
      - evince
      - file-roller
      - gdm
      - gedit
      - gnome-backgrounds
      - gnome-control-center
      - gnome-disk-utility
      - gnome-keyring
      - gnome-screenshot
      - gnome-shell
      - gnome-shell-extensions
      - gnome-terminal
      - gvfs-google
      - gvfs-mtp
      - gvfs-smb
      - nautilus
      - seahorse
      - xdg-user-dirs-gtk

- name: Install GNOME extra packages
  become: yes
  pacman:
    name:
      - arc-gtk-theme
      - dconf-editor
      - gnome-tweaks
      - python-psutil

- name: Install GNOME AUR packages
  aur:
    name:
      - gnome-shell-extension-dash-to-panel-git
      - gnome-shell-extension-openweather-git
      - gnome-shell-extension-sound-output-device-chooser-git
      - tela-icon-theme-git
    skip_installed: true

- name: Copy dconf user profile
  become: yes
  template:
    src: user
    dest: /etc/dconf/profile/user

- name: Create GNOME configuration directory
  become: yes
  file:
    path: /etc/dconf/db/gnome.d
    state: directory

- name: Copy GNOME configuration
  become: yes
  template:
    src: gnome.conf
    dest: /etc/dconf/db/gnome.d/00-desheffer
  notify:
    - Update dconf

- name: Copy dconf gdm profile
  become: yes
  template:
    src: gdm
    dest: /etc/dconf/profile/gdm

- name: Create GDM configuration directory
  become: yes
  file:
    path: /etc/dconf/db/gdm.d
    state: directory

- name: Copy GDM configuration
  become: yes
  template:
    src: gdm.conf
    dest: /etc/dconf/db/gdm.d/00-desheffer
  notify:
    - Update dconf

- name: Force reset favorite-apps
  dconf:
    key: /org/gnome/shell/favorite-apps
    state: absent
  changed_when: False

- name: Copy AccountServices configuration
  become: yes
  template:
    src: account
    dest: /var/lib/AccountsService/users/{{ ansible_user_id }}
    force: no

- name: Enable GDM service
  become: yes
  systemd:
    name: gdm.service
    enabled: yes
