---

- name: Install GNOME packages
  pacman:
    name: "{{ item }}"
  with_items:
    - arc-gtk-theme
    - gnome

- name: Install GNOME AUR packages
  become_user: "{{ user.name }}"
  aur:
    name: "{{ item }}"
  with_items:
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-topicons-plus-huttli-git
    - numix-icon-theme-pack-git

- name: Copy dconf user profile
  template:
    src: user
    dest: /etc/dconf/profile/user

- name: Create GNOME configuration directory
  file:
    path: /etc/dconf/db/gnome.d
    state: directory

- name: Copy GNOME configuration
  template:
    src: gnome.conf
    dest: /etc/dconf/db/gnome.d/00-desheffer
  notify:
    - Update dconf

- name: Start NetworkManager
  service:
    name: NetworkManager.service
    enabled: yes
    state: started
