---

- name: Copy pacman configuration
  become: yes
  template:
    src: pacman.conf
    dest: /etc/pacman.conf
  register: pacman_conf

- name: Update pacman cache
  become: yes
  pacman:
    update_cache: yes
  when: pacman_conf is changed

- name: Create pacman hook directory
  become: yes
  file:
    path: /etc/pacman.d/hooks
    state: directory

- name: Install reflector
  become: yes
  pacman:
    name: reflector

- name: Copy pacman mirrorlist hook
  become: yes
  template:
    src: mirrorlist.hook
    dest: /etc/pacman.d/hooks/mirrorlist.hook

- name: Force pacman mirrorlist update
  become: yes
  command: "pacman -S --noconfirm pacman-mirrorlist"

- name: Copy pacman systemd-boot hook
  become: yes
  template:
    src: systemd-boot.hook
    dest: /etc/pacman.d/hooks/systemd-boot.hook

- name: Install pacman-contrib
  become: yes
  pacman:
    name: pacman-contrib

- name: Enable paccache timer
  become: yes
  systemd:
    name: paccache.timer
    enabled: yes

- name: Compile with all cores
  become: yes
  lineinfile:
    path: /etc/makepkg.conf
    regexp: "^#?MAKEFLAGS=.*$"
    line: "MAKEFLAGS=\"-j$(nproc)\""

- name: Compress packages with all cores
  become: yes
  lineinfile:
      dest: /etc/makepkg.conf
      regexp: "^COMPRESSXZ"
      line: "COMPRESSXZ=(xz -c -z - --threads=0)"

- name: Copy yay configuration
  template:
    src: yay.json
    dest: ~/.config/yay/config.json
