---

- name: Create ~/rs directory
  file:
    path: ~/rs
    state: directory

- name: Create ~/.rs directory
  file:
    path: ~/.rs
    state: directory

- name: Link ~/.rs/.aws
  file:
    src: ~/.aws
    dest: ~/.rs/.aws
    state: link
    force: yes

- name: Create ~/.rs/.bash_history file
  copy:
    content: ""
    dest: ~/.rs/.bash_history
    force: no

- name: Create ~/.rs/.composer directory
  file:
    path: ~/.rs/.composer
    state: directory

- name: Link ~/.rs/.composer/auth.json
  file:
    src: ~/.config/composer/auth.json
    dest: ~/.rs/.composer/auth.json
    state: link
    force: yes

- name: Create ~/.rs/.gitignore file
  copy:
    content: ""
    dest: ~/.rs/.gitignore
    force: no

- name: Create ~/.rs/.ssh directory
  file:
    path: ~/.rs/.ssh
    state: directory

- name: Link ~/.rs/.ssh/id_rsa file
  file:
    src: ~/.ssh/id_ed25519-rsc-git
    dest: ~/.rs/.ssh/id_rsa
    state: link
    force: yes

- name: Create ~/.rs/.ssh/known_hosts file
  copy:
    content: ""
    dest: ~/.rs/.ssh/known_hosts
    force: no

- name: Create ~/.rs/.zsh_history file
  copy:
    content: ""
    dest: ~/.rs/.zsh_history
    force: no

- name: Copy heimdallr binary
  become: true
  get_url:
    url: "https://github.com/keelerm84/heimdallr/releases/download/0.2.0/heimdallr-x86_64-unknown-linux-musl"
    dest: /usr/local/bin/heimdallr
    mode: 0755
    force: no
