---

- name: Create RS directory
  file:
    path: ~/rs
    state: directory

- name: Clone heimdall repository
  git:
    repo: "https://github.com/needcaffeine/heimdall.git"
    dest: ~/rs/heimdall
    accept_hostkey: yes
    update: no

- name: Clone AWS rotate IAM keys repository
  git:
    repo: "https://github.com/rhyeal/aws-rotate-iam-keys"
    dest: ~/rs/aws-rotate-iam-keys
    accept_hostkey: yes
    update: no

- name: Create AWS rotate IAM keys cron
  cron:
    name: aws-rotate-iam-keys
    hour: "0"
    minute: "0"
    weekday: "0"
    job: "~/rs/aws-rotate-iam-keys/src/bin/aws-rotate-iam-keys"
