---

- name: Install NetworkManager
  become: yes
  pacman:
    name: networkmanager

- name: Enable NetworkManager service
  become: yes
  systemd:
    name: NetworkManager.service
    enabled: yes

- name: Copy resolvconf.conf
  become: yes
  template:
    src: resolvconf.conf
    dest: /etc/resolvconf.conf
    unsafe_writes: yes

- name: Copy rc-manager.conf
  become: yes
  template:
    src: rc-manager.conf
    dest: /etc/NetworkManager/conf.d/rc-manager.conf
