---

- name: Install TLP
  become: yes
  pacman:
    name: tlp

- name: Copy TLP configuration
  become: yes
  template:
    src: tlp.conf
    dest: /etc/default/tlp
  notify:
    - Restart TLP

- name: Start TLP
  become: yes
  systemd:
    name: tlp.service
    enabled: yes
    state: started

- name: Enable TLP sleep
  become: yes
  systemd:
    name: tlp-sleep.service
    enabled: yes

- name: Mask systemd radio service
  become: yes
  systemd:
    name: systemd-rfkill.service
    masked: yes

- name: Mask systemd radio socket
  become: yes
  systemd:
    name: systemd-rfkill.socket
    masked: yes
