#!/bin/bash

CURRENT_PROFILE=$(pacmd list-cards | grep "active profile" | cut -d ' ' -f 3-)

if [ "$CURRENT_PROFILE" = "<output:hdmi-stereo>" ]; then
    pacmd set-card-profile "alsa_card.pci-0000_00_1f.3" "output:analog-stereo+input:analog-stereo"
    pacmd set-sink-port "alsa_output.pci-0000_00_1f.3.analog-stereo" "analog-output-headphones"
else
    pacmd set-card-profile "alsa_card.pci-0000_00_1f.3" "output:hdmi-stereo"
fi
