#!/bin/bash

CURRENT_PROFILE=$(pacmd list-cards | grep "active profile:" | sed -ne 's/.*<\(.*\)>.*/\1/p')

CARD=$(pacmd list-cards | grep "name:" | sed -ne 's/.*<\(.*\)>.*/\1/p')

HDMI_PROFILE=""
if [ "$(cat /sys/class/drm/card0/card0-DP-1/status)" == "connected" ]; then
    HDMI_PROFILE="output:hdmi-stereo"
elif [ "$(cat /sys/class/drm/card0/card0-DP-2/status)" == "connected" ]; then
    HDMI_PROFILE="output:hdmi-stereo-extra1"
fi

ANALOG_PROFILE="output:analog-stereo+input:analog-stereo"

if [ "${CURRENT_PROFILE}" == "<${HDMI_PROFILE}>" ]; then
    pacmd set-card-profile "${CARD}" "${ANALOG_PROFILE}"
    pacmd set-sink-port "${CARD}.analog-stereo" "analog-output-headphones"
else
    pacmd set-card-profile "${CARD}" "${HDMI_PROFILE}"
fi
