---

- name: Install Docker
  become: yes
  pacman:
    name:
      - docker
      - docker-compose

- name: Add user to the docker group
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    append: yes
    groups: docker

- name: Create alternate Docker root directory
  file:
    path: "/home/{{ lookup('env', 'USER') }}/.docker-root"
    state: directory

- name: Relocate Docker root directory
  become: yes
  file:
    src: "/home/{{ lookup('env', 'USER') }}/.docker-root"
    dest: /var/lib/docker
    state: link

- name: Copy Docker daemon configuration
  become: yes
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Enable Docker service
  become: yes
  systemd:
    name: docker.service
    enabled: yes
