---

- name: Install Docker
  become: yes
  pacman:
    name:
      - docker
      - docker-compose

- name: Add user to the docker group
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    append: yes
    groups: docker

- name: Start Docker
  become: yes
  systemd:
    name: docker.service
    enabled: yes
    state: started
