---

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Install base packages
  pacman:
    name: "{{ item }}"
  with_items:
    - base-devel
    - bash
    - bash-completion
    - bc
    - coreutils
    - git
    - jq
    - rsync
    - the_silver_searcher
    - tmux
    - tree
    - vim
    - yay

- include: user.yml
