---

- name: Copy pacman configuration
  become: yes
  template:
    src: pacman.conf
    dest: /etc/pacman.conf
  register: pacman_conf

- name: Update pacman cache
  become: yes
  pacman:
    update_cache: yes
  when: pacman_conf is changed

- name: Create pacman hook directory
  become: yes
  file:
    path: /etc/pacman.d/hooks
    state: directory

- name: Install pacman hook to update systemd-boot
  aur:
    name: systemd-boot-pacman-hook

- name: Copy pacman hook to update mirror list
  become: yes
  template:
    src: mirrorlist.hook
    dest: /etc/pacman.d/hooks/mirrorlist.hook
