---

- name: Install base packages
  pacman:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - base-devel
    - bash
    - bash-completion
    - bc
    - coreutils
    - dialog
    - fwupd
    - git
    - git
    - htop
    - jq
    - net-tools
    - rsync
    - the_silver_searcher
    - tmux
    - tree
    - wireless_tools
    - wpa_supplicant

- name: Install yay
  become_user: "{{ user.name }}"
  aur:
    name: yay
    use: makepkg
    skip_installed: yes
