---

- name: Set kernel parameters
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    state: present
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ kernel_parameters }}\""
  notify:
    - Rebuild GRUB

- name: Set timeout
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_TIMEOUT="
    state: present
    line: "GRUB_TIMEOUT=1"
  notify:
    - Rebuild GRUB

- name: Set timeout style
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_TIMEOUT_STYLE="
    state: present
    line: "GRUB_TIMEOUT_STYLE=\"hidden\""
  notify:
    - Rebuild GRUB
