---

- name: Install font packages
  become: yes
  pacman:
    name:
      - cantarell-fonts
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - ttf-dejavu
      - ttf-droid
      - ttf-liberation
      - ttf-roboto
      - ttf-ubuntu-font-family

- name: Install font AUR packages
  aur:
    name:
      - nerd-fonts-fira-code
      - ttf-ms-fonts
      - ttf-vista-fonts

- name: Apply local font configuration
  become: yes
  template:
    src: local.conf
    dest: /etc/fonts/local.conf
