---

- name: Install font packages
  become: yes
  pacman:
    name: "{{ item }}"
  with_items:
    - cantarell-fonts
    - ttf-dejavu
    - ttf-liberation
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji

- name: Install font AUR packages
  aur:
    name: "{{ item }}"
  with_items:
    - nerd-fonts-dejavu-complete

- name: Apply local font configuration
  become: yes
  template:
    src: local.conf
    dest: /etc/fonts/local.conf

- name: Enable sub-pixel rendering
  become: yes
  file:
    src: /etc/fonts/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    state: link

- name: Enable hinting
  become: yes
  file:
    src: /etc/fonts/conf.avail/10-hinting-slight.conf
    dest: /etc/fonts/conf.d/10-hinting-slight.conf
    state: link

- name: Enable LCD filter
  become: yes
  file:
    src: /etc/fonts/conf.avail/11-lcdfilter-default.conf
    dest: /etc/fonts/conf.d/11-lcdfilter-default.conf
    state: link
