---

- name: Install CLI packages
  become: yes
  pacman:
    name:
      - aws-cli
      - bc
      - coreutils
      - curl
      - entr
      - file
      - fwupd
      - git
      - htop
      - jq
      - lastpass-cli
      - lsof
      - man-db
      - man-pages
      - mlocate
      - netcat
      - python
      - rsync
      - sshpass
      - sudo
      - tree
      - wget
      - yq
