---

- name: Install CLI packages
  become: yes
  pacman:
    name:
      - aws-cli
      - bat
      - bc
      - coreutils
      - curl
      - entr
      - exa
      - expect
      - file
      - fwupd
      - git
      - git-delta
      - github-cli
      - htop
      - jq
      - lastpass-cli
      - lsof
      - man-db
      - man-pages
      - mlocate
      - netcat
      - python
      - python-hjson
      - rsync
      - sshpass
      - sudo
      - tree
      - wget

- name: Install extra CLI packages
  aur:
    name:
      - go-yq-bin
      - google-cloud-sdk
