---

- name: Install CLI packages
  become: yes
  pacman:
    name:
      - aws-cli
      - bash
      - bc
      - coreutils
      - curl
      - dnsutils
      - fwupd
      - git
      - htop
      - jq
      - lastpass-cli
      - lsof
      - mlocate
      - net-tools
      - netcat
      - python
      - rsync
      - sudo
      - tree
      - wget
      - wireless_tools
      - wpa_supplicant
