---

- name: Install CLI packages
  become: yes
  pacman:
    name:
      - aws-cli
      - bc
      - fwupd
      - htop
      - jq
      - mlocate
      - netcat
      - reflector
      - rsync
      - tree
