---

- name: Install CLI packages
  become: yes
  pacman:
    name:
      - aws-cli
      - bash
      - bc
      - coreutils
      - curl
      - dnsutils
      - fwupd
      - git
      - htop
      - jq
      - lastpass-cli
      - lsof
      - mlocate
      - net-tools
      - netcat
      - networkmanager
      - python
      - rsync
      - sshpass
      - sudo
      - tree
      - wget
      - wireless_tools
      - wpa_supplicant

- name: Enable NetworkManager service
  become: yes
  systemd:
    name: NetworkManager.service
    enabled: yes
